version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
      - ./backend/static:/app/static
      - backend-node-modules:/app/node_modules
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - SECRET_KEY=dev_secret_key_change_in_production
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
      - CORS_ALLOWED_ORIGINS=http://localhost:3000

  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    stdin_open: true
    command: npm start

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  backend-node-modules:
  frontend-node-modules: